language: objective-c
osx_image: xcode61
rvm:
    - 2.4
install:
    - ./scripts/install.sh
before_script:
  # Work around travis problem with shell-session-update on OSX
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then unset -f cd; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then shell_session_update() { :; }; fi
script:
  # Work around travis problem with shell-session-update on OSX
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then unset -f cd; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then shell_session_update() { :; }; fi
  - ./scripts/build.sh
